-- SQL Migration Script for NHT Athena Supabase Tables
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. briefs
CREATE TABLE IF NOT EXISTS briefs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    gemini_brief TEXT,
    athena_synthesis TEXT,
    states JSONB
);

-- 2. feedback
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    feedback TEXT NOT NULL
);

-- 3. drafts
CREATE TABLE IF NOT EXISTS drafts (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    channel TEXT,
    recipient TEXT,
    status TEXT,
    payload TEXT,
    integration TEXT,
    broadcast_type TEXT,
    repeat_tomorrow BOOLEAN DEFAULT FALSE
);

-- 4. priorities
CREATE TABLE IF NOT EXISTS priorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    text TEXT NOT NULL,
    urgent BOOLEAN DEFAULT FALSE,
    actioned BOOLEAN DEFAULT FALSE
);

-- 5. rl_signals
CREATE TABLE IF NOT EXISTS rl_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    type TEXT NOT NULL,
    weight INTEGER NOT NULL,
    data JSONB
);

-- 6. offline_queue
CREATE TABLE IF NOT EXISTS offline_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    text TEXT NOT NULL,
    synced BOOLEAN DEFAULT FALSE
);

-- 7. oauth_tokens (for Google OAuth)
CREATE TABLE IF NOT EXISTS oauth_tokens (
    user_id TEXT PRIMARY KEY,
    token_data JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
